### PR TITLE
Opens the generated file after selecting a problem

### PR DESCRIPTION
**Pull request by thenicealex**
Hi! Love the plugin!

Just made a quick PR that allows edit file after Selecting a problem in pop windows.
This is my first contribution using Lua so if I missed anything or if there are any issues please let me know.

by the way, I accidentally formatted the file with stylua tool. What I modified is lines 92 to 113 in popup/init.lua and README.

edit.gif is the show.

### CODE REVIEW

**Comment by thenicealex** [comment]
i am very sorry! i made a mistake.
please close this pr.

**Comment by thenicealex** [comment]
I made some changes to the previous changes and added the default configuration file. Editing the file is also in effect.
I just using it in windows, I don't know of any cases on other operating systems. If there are some errors, please let me know in time. Thanks.

**Comment by thenicealex** [comment]
my config:
```lua
{
  dir = "D:/workstation/github/leetup.nvim",
  dependencies = { { "m00qek/baleia.nvim" }, },
  opts = {
    language = "cpp",
      floating_window = {
	 borderchars = {
		r = "─",
		l = "│",
		ul = "╭",
		ur = "╮",
		dr = "╯",
		dl = "╰",
	 },
      },
  },
  config = function(_, opts)
	require("leetup").setup(opts)
  end,
},
```

**Comment by dragfire** [comment]
Thank you @thenicealex 💯

**Pull request merged**
